codelearncreate/c2lc-coding-environment

src/App.js
Removed unused components and states for 0.1 release. 
Some update to a handler 'handleClickRun()' to check if dash is connected first:
`
handleClickRun = () => {
if (this.state.dashConnectionStatus === 'connected') {
this.interpreter.run(this.state.program);
}
};
`
Without checking the connection, errors will occur, since the interpreter doesn't know any commands until dash is connected from componentDidUpdate() in App.js
=> C2LC-37: Remove components not used in 0.1 from App.js

public/index.html, public/manifest.json, src/messages.json
On:
HTML page title
H1 heading
public/manifest.json
=> C2LC-101: Change title to 'Inclusive Coding Environment'

package-lock.json, package.json, public/index.html, src/index.js
Decided to use typeface-roboto to store roboto font locally and use default service worker created by CRA's build script.
=> C2LC-163: Turn the coding environment into PWA

src/App.js, src/ProgramBlockEditor.js, src/ProgramBlockEditor.test.js
Move the addNodeExpandedMode state to the App, and set it to true by default.
=> C2LC-229: Move addNodeExpandedMode to App and default to true

src/AudioManager.js
See [C2LC-257](https://issues.fluidproject.org/browse/C2LC-257) for details.
=> C2LC-257: Disable movement sounds when audio is disabled.

package.json, src/AddModeImage.js, src/App.js, src/App.test.js, src/CharacterState.test.js, src/DeleteModeImage.js, src/DeviceConnectControl.js, src/FocusTrapManager.test.js, src/ProgramUtils.test.js, src/Scene.js, src/Scene.test.js, src/ShareCompleteModal.js, src/serviceWorker.js
See [C2LC-277](https://issues.fluidproject.org/browse/C2LC-277) for details.
=> C2LC-277: Add indentation linting rules.

src/ShareButton.css
Commit message has wrong issue number
=> C2LC-300: Update focus/hover styles of ShareButton

src/App.js, src/App.test.js, src/AudioManagerImpl.js, src/FakeAudioManager.js, src/ProgramBlockEditor.test.js, src/types.js
See [C2LC-310](https://issues.fluidproject.org/browse/C2LC-310) for details.
=> C2LC-310: Updated audio toggle to only control announcements.

src/AllowedActionsSerializer.js, src/App.js, src/C2lcURLParams.test.js
See [C2LC-318](https://issues.fluidproject.org/browse/C2LC-318) for details.
=> C2LC-318: Disentangled exception-throwing parameter checks.

public/index.html
See [C2LC-314](https://issues.fluidproject.org/browse/C2LC-314) for details.
=> C2LC-314: Change page title to 'Weavly'.

src/svg/Pause.svg
See [C2LC-325](https://issues.fluidproject.org/browse/C2LC-325) for details.
=> C2LC-325: Removed filters from pause icon.

src/Character.scss
See [C2LC-326](https://issues.fluidproject.org/browse/C2LC-326) for details.
=> C2LC-326: Fixed issues with stroke-width CSS rules and rabbit icon.

src/WorldSelector.js, src/WorldSelector.scss, src/WorldSelector.test.js
See [C2LC-324](https://issues.fluidproject.org/browse/C2LC-324) for details.
=> C2LC-324: Commented out world picker header icon.

src/App.js
See [C2LC-321](https://issues.fluidproject.org/browse/C2LC-321) for details.
=> C2LC-321: Fixed default theme.

src/App.scss
=> C2LC-323: Remove unnecessarily whitespace at the bottom of Actions Panel

src/ProgramBlockEditor.js, src/ToggleSwitch.js, src/ToggleSwitch.test.js, src/WorldSelector.test.js
See [C2LC-342](https://issues.fluidproject.org/browse/C2LC-342) for details.
=> C2LC-342: Ensure that all buttons and toggles support both space and enter keys.

src/StopButton.scss
See [C2LC-340](https://issues.fluidproject.org/browse/C2LC-340) for details.
=> C2LC-340: Adjusted margin of stop button.

src/App.js, src/AudioManagerImpl.test.js, src/CharacterState.test.js, src/CharacterStateSerializer.test.js, src/ProgramBlockEditor.test.js, src/Scene.js, src/Scene.test.js, src/SceneDimensions.js, src/SceneDimensions.test.js
See [C2LC-372](https://issues.fluidproject.org/browse/C2LC-372) for details.
=> C2LC-372: parameterised scene dimension minX and minY values.

src/ProgramBlockEditor.js, src/ProgramBlockEditor.test.js
See [C2LC-366](https://issues.fluidproject.org/browse/C2LC-366) for more information.
=> C2LC-366: Fixed announcement when replace button is hit and no command is selected.

package.json, src/App.js, src/AudioManagerImpl.test.js, src/FakeRobotDriver.js, src/serviceWorker.js
See [C2LC-394](https://issues.fluidproject.org/browse/C2LC-394) for details.
=> C2LC-394: Enabled linting errors for stray console statements.

src/ProgramBlockEditor.js, src/ProgramBlockEditor.test.js
See [C2LC-397](https://issues.fluidproject.org/browse/C2LC-397) for details.
=> C2LC-397: Change the label for the add node when adding to an empty program

src/_variables.scss
See [C2LC-376](https://issues.fluidproject.org/browse/C2LC-376) for details.
=> C2LC-376: Update colours of forward and backward commands

src/App.js, src/App.scss
See [C2LC-396](https://issues.fluidproject.org/browse/C2LC-396) for details.
=> C2LC-396: Change the document/tab order of the application

src/Themes.scss
See [C2LC-408](https://issues.fluidproject.org/browse/C2LC-408) for details.
=> C2LC-408: Change the character position controls' colour

docs/keyboard.md, src/AddNode.js, src/App.js, src/KeyboardInputSchemes.js, src/ProgramBlockEditor.js
See [C2LC-411](https://issues.fluidproject.org/browse/C2LC-411) for details.
=> C2LC-411: Add keyboard shortcut for delete program step

src/KeyboardInputSchemes.js
See https://issues.fluidproject.org/browse/C2LC-418
=> C2LC-418: Shortcuts are not working from Grid 3 in Chrome and Edge

docs/keyboard.md
See [C2LC-417](https://issues.fluidproject.org/browse/C2LC-417) for details.
=> C2LC-417: Updated wording to reflect new default keyboard input scheme and provide better instructions.

docs/keyboard.md, src/App.js, src/CharacterPositionController.js, src/KeyboardInputSchemes.js
See [C2LC-424](https://issues.fluidproject.org/browse/C2LC-424) for details.
=> C2LC-424: Added keyboard shortcuts to focus on character position text inputs.

src/App.js
See [C2LC-409](https://issues.fluidproject.org/browse/C2LC-409) for details.
=> C2LC-409: Disable edits to program and character state while program is running

public/_redirects
@michelled could you merge this, thanks!
=> C2LC-423: Force redirect to weavly.org

src/App.js
See [C2LC-426](https://issues.fluidproject.org/browse/C2LC-426) for details.
=> C2LC-426: Close action panel when play button is clicked

src/App.js, src/App.test.js, src/KeyboardInputSchemes.js, src/KeyboardInputSchemes.test.js
See [C2LC-416](https://issues.fluidproject.org/browse/C2LC-416) for details.
=> C2LC-416: Escape out of partially entered keyboard shortcuts.

src/App.js, src/App.scss, src/Scene.js, src/Scene.scss, src/Scene.test.js, src/_variables.scss
See [C2LC-447](https://issues.fluidproject.org/browse/C2LC-447) for details.
=> C2LC-447: Reduce the number of grid squares (increase size)

src/App.js, src/App.test.js, src/KeyboardInputModal.js
See [C2LC-446](https://issues.fluidproject.org/browse/C2LC-446) for details.
=> C2LC-446: Added persistence for keyboard settings.

docs/keyboard.md, src/App.js, src/App.test.js
See [C2LC-458](https://issues.fluidproject.org/browse/C2LC-458) for details.
=> C2LC-458: Disable key bindings by default.

src/ShareButton.scss, src/Themes.scss
See [C2LC-398](https://issues.fluidproject.org/browse/C2LC-398) for details.
=> C2LC-398: Fixed hover styles for share button in light theme.

src/WorldSelector.scss
See [C2LC-459](https://issues.fluidproject.org/browse/C2LC-459) for details.
=> C2LC-459: Fixed blurry world picker radio buttons on iOS.

src/KeyboardInputModal.js
See [C2LC-477](https://issues.fluidproject.org/browse/C2LC-477) for details.
=> C2LC-477: Fix NVDA issue in the keyboard setting modal

src/CharacterPositionController.js, src/CharacterPositionController.scss, src/ProgramBlockEditor.js, src/ProgramBlockEditor.scss, src/Themes.scss, src/Worlds.scss
See [C2LC-460](https://issues.fluidproject.org/browse/C2LC-460) for details
=> C2LC-460: Update background of character icons 

src/Worlds.scss
See [C2LC-465](https://issues.fluidproject.org/browse/C2LC-465) for details.
=> C2LC-465: Update drawing path in high contrast theme 

src/Worlds.scss
See [C2LC-469](https://issues.fluidproject.org/browse/C2LC-469) for details.
=> C2LC-469: Update grid line colour in the high contrast theme

src/ActionsMenu.js, src/ActionsMenu.test.js, src/App.js, src/ProgramChangeController.js, src/ProgramSequence.js, src/ProgramSequence.test.js
See [C2LC-491](https://issues.fluidproject.org/browse/C2LC-491) for details.
=> C2LC-491: Updated to avoid tracking used actions separately.

src/ConfirmDeleteAllModal.js, src/ConfirmDeleteAllModal.scss, src/ModalFooter.scss, src/ShareButton.scss, src/ThemeSelector.scss
See [C2LC-480](https://issues.fluidproject.org/browse/C2LC-480) for details.
=> C2LC-480: Update text colours in different UI components

src/App.js
See [C2LC-494](https://issues.fluidproject.org/browse/C2LC-494) for more details.
=> C2LC-494: Always allow unhiding of hidden actions.

src/App.js, src/IconButton.js
See [C2LC-486](https://issues.fluidproject.org/browse/C2LC-486) for details.
=> C2LC-486: Fix broken keyboard shortcuts

src/App.js, src/App.scss
See [C2LC-473](https://issues.fluidproject.org/browse/C2LC-473) for details.
=> C2LC-473: Removed world thumbnail from right-hand panel.

src/KeyboardInputModal.scss
See [C2LC-471](https://issues.fluidproject.org/browse/C2LC-471) for details.
=> C2LC-471: Tamed keyboard input modal styles breaking other modals.

src/ShareCompleteModal.css
See [C2LC-472](https://issues.fluidproject.org/browse/C2LC-472) for details.
=> C2LC-472: Fixed padding of share confirmation dialog.

src/messages.json
See [C2LC-518](https://issues.fluidproject.org/browse/C2LC-518) for details.
=> C2LC-518: Update aria-label of the delete all button

src/ActionPanel.js, src/App.js, src/ConfirmDeleteAllModal.js, src/FocusTrapManager.js, src/KeyboardInputModal.js, src/ShareCompleteModal.js, src/Utils.js, src/Utils.test.js, src/WorldSelector.js
See [C2LC-493](https://issues.fluidproject.org/browse/C2LC-493) for details.
=> C2LC-493: Consolidated focus functions.

src/ProgramBlockEditor.js, src/ProgramBlockEditor.scss, src/messages.json
See [C2LC-503](https://issues.fluidproject.org/browse/C2LC-503) for details.
=> C2LC-503: Collapsed 'start' icon so that it doesn't look like a button.

src/ConfirmDeleteAllModal.js, src/ConfirmDeleteAllModal.scss, src/ModalBody.css, src/ModalBody.js, src/ModalHeader.scss, src/ModalWithFooter.scss, src/WorldSelector.js
See [C2LC-546](https://issues.fluidproject.org/browse/C2LC-546) for details.
=> C2LC-546: Implement a scrollable container for modal content

src/WorldSelector.js
See [C2LC-541](https://issues.fluidproject.org/browse/C2LC-541) for details.
=> C2LC-541: Update world picker to display more than four worlds

src/KeyboardInputModal.js
See [C2LC-566](https://issues.fluidproject.org/browse/C2LC-566) for details.
=> C2LC-566: Fix focus when keyboard input modal is closed.

src/CharacterPositionController.js, src/CharacterPositionController.scss, src/CharacterPositionController.test.js, src/Scene.js, src/Scene.test.js, src/Worlds.js
Enable flipping of the character in all current worlds except for the Landmarks world.
=> C2LC-561: Enable character flipping per world

src/ActionPanel.js
See [C2LC-584](https://issues.fluidproject.org/browse/C2LC-584) for details.
=> C2LC-584: Hide replace button for start and end loop blocks.

src/ProgramSerializer.js, src/ProgramSerializer.test.js
See [C2LC-604](https://issues.fluidproject.org/browse/C2LC-604) for details.
=> C2LC-604: Update ProgramSerializer to serialize 0 iteration loops

src/ProgramSequence.js, src/ProgramSequence.test.js
See [C2LC-601](https://issues.fluidproject.org/browse/C2LC-601) for details.
=> C2LC-601: Support program step replacement with loop command

src/LoopIterationsInput.js
See [C2LC-602](https://issues.fluidproject.org/browse/C2LC-602) for details.
=> C2LC-602: Stop event propagation from LoopIterationsInput on click

src/Worlds.js
See [C2LC-482](https://issues.fluidproject.org/browse/C2LC-482) for details.
=> C2LC-482: Change starting position for the Sketchpad to A2

src/LoopIterationsInput.js, src/ProgramParser.js, src/ProgramParser.test.js
See [C2LC-603](https://issues.fluidproject.org/browse/C2LC-603) for details.
=> C2LC-603: Disallow 0 number of iterations for loop

src/App.js
See [C2LC-619](https://issues.fluidproject.org/browse/C2LC-619) for details.
=> C2LC-619: Disallow refresh of the scene when program is paused

src/LoopIterationsInput.js
See [C2LC-628](https://issues.fluidproject.org/browse/C2LC-628) for details.
=> C2LC-628: Add additional dataset properties to LoopIterationsInput to support the program modification keyboard shortcuts

src/CharacterState.js
See [C2LC-623](https://issues.fluidproject.org/browse/C2LC-623) for details.
=> C2LC-623: Increase max number of path segments.

src/ProgramSequence.js, src/ProgramSequence.test.js
See [C2LC-591](https://issues.fluidproject.org/browse/C2LC-591) for details.
=> C2LC-591: Reset loop label to A when there are no loops in the program

src/App.js, src/C2lcURLParams.js, src/C2lcURLParams.test.js, src/Scene.js, src/Scene.scss, src/Scene.test.js, src/Utils.js, src/Utils.test.js, src/Worlds.scss
See [C2LC-631](https://issues.fluidproject.org/browse/C2LC-631) for details.
=> C2LC-631: Update starting position of the characters when they are moved by CharacterPositionController

src/Scene.js
See [C2LC-645](https://issues.fluidproject.org/browse/C2LC-645) for details.
=> C2LC-645: Fix an UI issue on iPads

src/ProgramBlockEditor.js, src/ProgramBlockEditor.scss, src/ProgramBlockEditor.test.js, src/Themes.scss, src/index.scss
See [C2LC-590](https://issues.fluidproject.org/browse/C2LC-590) for details.
=> C2LC-590: Wrap loop pairs in separate containers and add focus style on the container

src/ProgramBlockEditor.js, src/ProgramBlockEditor.scss, src/ProgramBlockEditor.test.js, src/Themes.scss, src/index.scss
See [C2LC-592](https://issues.fluidproject.org/browse/C2LC-592) for details.
=> C2LC-592: Render outer loops differently from nested loops

src/ProgramBlockEditor.js, src/ProgramBlockEditor.scss, src/ProgramBlockEditor.test.js, src/Themes.scss
See [C2LC-643](https://issues.fluidproject.org/browse/C2LC-643) for details.
=> C2LC-643: Add highlight on active loop containers

src/AudioManagerImpl.js, src/Utils.js, src/Utils.test.js
See https://issues.fluidproject.org/browse/C2LC-668
=> C2LC-668: Add logic to select voice for announcement

src/ActionsMenuItem.scss, src/ThemeSelector.scss, src/Themes.scss
See [C2LC-674](https://issues.fluidproject.org/browse/C2LC-674) for details.
=> C2LC-674: Update hover styles for ThemeSelector options in different themes

src/Scene.js
And scroll the character into view when design mode is exited.
=> Scroll the design mode cursor into view (fixes #448)
